version: '3.8'

services:
  # MySQL
  mysql:
    image: mysql:5.7
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stationSki
      MYSQL_USER: root
      MYSQL_PASSWORD:  
    ports:
      - "3306:3306"  

  #Spring
  spring-boot-app:
    image: rayenkhadraoui/skierrepository:latest  # Use your Spring Boot image name
    container_name: my-spring-boot-container
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/stationSki?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=  
    ports:
      - "8089:8089"  
    depends_on:
      - mysql  

volumes:
  mysql-data: