version: "3.8"
services:
  gestion-station-ski:
    depends_on:
      - mysqldb
    image: ahmedbenabdallah-5sae4-g3-ski:latest
    restart: on-failure
    environment:
      SPRING_APPLICATION_JSON: '{
                 "spring.datasource.url" : "jdbc:mysql://mysqldb:3306/stationSki?createDatabaseIfNotExist=true",
                 "spring.datasource.username" : "root",
                 "spring.jpa.show-sql" : "true",
                 "spring.jpa.hibernate.ddl-auto" : "update",
                 "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect"
               }'
    ports:
      - "8089:8089"
    stdin_open: true
    tty: true

  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
