version: '3.8'

services:
  # MySQL
  mysql:
    image: mysql:latest
    container_name: my-mysql-container
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: stationSki
    ports:
      - "3306:3306"  

#Spring
  spring-boot-app:
    image: rayenkhadraoui/skierrepository:latest  
    container_name: spring-boot-container
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/stationSki?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=  
    ports:
      - "8089:8089"  
    depends_on:
      - mysql  

volumes:
  mysql-data:
  

